# Module 4: How to work with data
- Loading data with Python's built-in functions
- Using libraries like Numpy and Pandas
- Application Programming Interfaces (APIs)

## Reading Files with Open

In [9]:
import os
print(os.getcwd())


/Users/lucie/Desktop/Github/python_for_ds


In [15]:
# using open function
file1 = open("data/example1.txt","r") # r= reading, w 'writing, a = appending

In [16]:
file1.name
file1.mode

'r'

In [17]:
file1.close()

In [19]:
with open("data/Example1.txt","r") as file1:
    file_stuff = file1.read() # stores file content
    print(file_stuff) 
print(file1.closed)
print(file_stuff)

test
True
test


In [21]:
with open("data/Example1.txt","r") as file1:
    file_stuff = file1.readline(16) # first 16 characters of first line
    print(file_stuff)

test


In [23]:
with open("data/Example1.txt","r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1

Iteration 0 :  test


#### excercise 1

In [13]:
from pyodide.http import pyfetch

import pandas as pd


ModuleNotFoundError: No module named 'pyodide'

In [ ]:

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/example1.txt"

async def download(url, filename):

    response = await pyfetch(url)

    if response.status == 200:

        with open(filename, "wb") as f:

            f.write(await response.bytes())

await download(filename, "example1.txt")

print("done")


#### Writing files with Open

In [26]:
file1 = open("data/Example1.txt","w")

In [27]:
with open("data/Example1.txt","w") as file1:
    file1.write("this is line A\n")
    file1.write("this is line B\n")

In [31]:
Lines = ["this is line A\n", "this is line B\n"]
with open("data/Example1.txt","w") as file1:
    for line in Lines:
        file1.write(line)

#### Append

In [33]:
with open("data/Example1.txt","a") as file1:
    file1.write("this is line C\n")

In [34]:
file1.name

'data/Example1.txt'

In [35]:
file1.mode

'a'

In [37]:
file1.close()

# Pandas

In [ ]:
#conda activate pythonProject3
#conda install pandas

In [1]:
import pandas as pd

In [6]:
csv_path = 'data/file1.csv'

In [7]:
df=pd.read_csv(csv_path)

EmptyDataError: No columns to parse from file

In [11]:
songs={'Album':['Thriller','Back in Black'],
       'Released':[1982,1980],
       'Length':['00:42:19','00:42:11']}
songs_frame=pd.DataFrame(songs)

In [13]:
songs_frame.head()

Album  Released    Length
0       Thriller      1982  00:42:19
1  Back in Black      1980  00:42:11

In [17]:
x=songs_frame[['Length','Released']]

In [18]:
x

Length  Released
0  00:42:19      1982
1  00:42:11      1980

In [23]:
#songs_frame.iloc[0,0] 
songs_frame.iloc[1,0]  # row index: 1, column index: 0

'Back in Black'

In [46]:
songs={'Album':['Thriller','Back in Black'],
       'Released':[1982,1980],
       'Length':['00:42:19','00:42:11']}
songs_frame=pd.DataFrame(songs)

In [34]:
df_new= songs_frame
df_new

Album  Released    Length
0       Thriller      1982  00:42:19
1  Back in Black      1980  00:42:11

In [36]:
df_new.index=['a','b']
df_new

Album  Released    Length
a       Thriller      1982  00:42:19
b  Back in Black      1980  00:42:11

In [40]:
df_new.loc['a','Album']
df_new.loc['b','Released']

1980

In [45]:
# slicing dataframes
z=df_new.iloc[0:1,0:2]
z

Album  Released
a  Thriller      1982

#### Working with and Saving Data

In [48]:
df_new['Released'].unique()

array([1982, 1980])

In [49]:
df_new['Released']>1870

a    True
b    True
Name: Released, dtype: bool

In [50]:
df=songs_frame
df1=df[df['Released']>1870]
df1

Album  Released    Length
0       Thriller      1982  00:42:19
1  Back in Black      1980  00:42:11

In [53]:
df1.to_csv('outputs/new_songs.csv')

In [ ]:
#Question 5
#Assume that you have a data frame containing details of various musical artists, their famous albums, their genres, and various other parameters. Here, `Album` is the second column. How do we retrieve records from row 3 through row 6? 
df.loc[2:5, ‘Album’]

In [54]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [55]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

ID
0   1
1   2
2   3
3   4

In [56]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [57]:
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1

Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [58]:
b = df1[['Marks']]
b

Marks
0    85
1    72
2    89
3    76

In [59]:
c = df1[['Country','Course']]
c

Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [60]:
x = df1['Student']
x


0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: object

# Numpy

### 1D Numpy (ND arrays)

In [61]:
# import numpy library

import numpy as np 

In [63]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [65]:
a[0]


a[1]: 1


In [ ]:
# Print element
print("a[1]:", a[1])


In [66]:
# checking NumPy version
print(np.__version__)

1.24.3


In [67]:
# Check the type of the array
type(a)

numpy.ndarray

In [69]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int64')

In [70]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [73]:
# check type of array
type(b)
b.dtype

dtype('float64')

In [74]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [75]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [76]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [77]:
a = np.array([10, 2, 30, 40,50])
# assign the value 20 as 2nd element
a[1] = 20
a

array([10, 20, 30, 40, 50])

In [78]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [79]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [82]:
# defining slicing steps
arr= np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) # start:end:step

[2 4]


In [83]:
# if not passed start its considered 0
print(arr[:4])

[1 2 3 4]


In [84]:
# if not passed end it considers till the length of array
print(arr[4:])

[5 6 7]


assign value with list

In [86]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [87]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

In [89]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

other attributes

In [90]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [93]:
# Get the size of numpy array
a.size

5

In [94]:
# Get the number of dimensions of numpy array
a.ndim

1

In [95]:
# Get the shape/size of numpy array
a.shape

(5,)

In [97]:
b = np.array([10, 20, 30, 40, 50, 60, 70])
b.size
b.ndim
b.shape

(7,)

(7,)

#### Numpy statistical functions

Vector addition and substraction

In [98]:
a=np.array([0,1]) 

b=np.array([1,0]) 

np.dot(a,b) 

0

In [99]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[0,1],[1,0]]) 

Z=X+Y 

In [101]:
Z

array([[1, 1],
       [1, 1]])

In [102]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]

In [103]:
out

array([1, 2])

In [104]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 

In [105]:
Z

array([[2, 2],
       [2, 2]])

In [110]:
with open("Example1.txt","r") as file1: 

     FileContent=file1.read() 


     print(FileContent) 

FileNotFoundError: [Errno 2] No such file or directory: 'Example1.txt'

In [111]:
with open(example1,"r") as file1: 

SyntaxError: unexpected EOF while parsing (2574568412.py, line 1)